[fix issue #1180] Too many update operation violates with apiserver concurrency...
fluid-cloudnative/fluid pull request #1184
Opened 2021-11-23 14:16 UTC by daomin885

Signed-off-by: 道民 <jiebin.cjb@alibaba-inc.com>

### Ⅰ. Describe what this PR does

### Ⅱ. Does this pull request fix one issue?
fixes #1180

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2021-11-23 15:30 UTC, cheyang requested changes

2021-11-23 15:44 UTC, cheyang commented on pkg/ddc/alluxio/worker.go
> +			_ = utils.LoggingErrorExceptConflict(e.Log, err, "Failed to check worker ready", types.NamespacedName{Namespace: e.namespace, Name: e.name})
I think you don't need to call `utils.LoggingErrorExceptConflict` in line 44.

2021-11-23 16:29 UTC, daomin885 commented on pkg/ddc/alluxio/health_check.go
> +				_ = utils.LoggingErrorExceptConflict(e.Log, updateErr, "Failed to update runtime status", types.NamespacedName{Namespace: e.namespace, Name: e.name})
good suggestion!

2021-11-25 03:38 UTC, cheyang requested changes

2021-11-25 03:38 UTC, cheyang commented on pkg/ddc/alluxio/worker.go
> +			_ = utils.LoggingErrorExceptConflict(e.Log, err, "Failed to check worker ready", types.NamespacedName{Namespace: e.namespace, Name: e.name})
I suggest to remove 

```
if err != nil {
			_ = utils.LoggingErrorExceptConflict(e.Log, err, "Failed to check worker ready", types.NamespacedName{Namespace: e.namespace, Name: e.name})
```

2021-11-25 04:08 UTC, daomin885 commented on pkg/ddc/alluxio/worker.go
> +			_ = utils.LoggingErrorExceptConflict(e.Log, err, "Failed to check worker ready", types.NamespacedName{Namespace: e.namespace, Name: e.name})
thanks, i will remove it~

2021-11-25 05:14 UTC, cheyang approved these changes

2021-11-25 05:14 UTC, merged