Fix update dataload status error
fluid-cloudnative/fluid pull request #1433
Opened 2022-02-11 06:59 UTC by abowloflrf

Signed-off-by: Ruofeng Lei <ruofenglei@outlook.com>

### Ⅰ. Describe what this PR does

Dataload controller try to update the `Dataload` status using name/namespace in `ctx` which is the name of `Dataset` but not `Dataload`

Fix this by replacing `ctx` with `targetDataload`

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2022-02-11 09:38 UTC, TrafalgarZZZ requested changes
Thanks for reporting and fixing this bug!

I think it's a mistake that `ctx.Name` and `ctx.Namespace` is the name and namespace of the target dataset. It should be the one of the reconciling dataload.

So I think we may change `ctx.NamespacedName` [here](https://github.com/fluid-cloudnative/fluid/blob/master/pkg/controllers/v1alpha1/dataload/dataload_controller.go#L112), and keep `implement.go` same as before

2022-02-11 11:56 UTC, TrafalgarZZZ commented
> > Thanks for reporting and fixing this bug!
> > I think there are still some similar mistakes in `implement.go` too, would you like also fix that?
> 
> OK I'll check and fix that.
> 
> BTW, I noticed that you suggest to change the `NamespacedName` in the `ctx`. Should I change it to `Dataload`'s name or keep as the `Dataset`'s name? Which should be better?

Sorry to give an improper suggestion at first. After then I double checked the code and found the `ctx` will be used somewhere else(for example, [here](https://github.com/fluid-cloudnative/fluid/blob/master/pkg/controllers/v1alpha1/dataload/dataload_controller.go#L157)), and it requires `ctx.Name` should be `Dataset`'s name. So I think it's better to keep it as the `Dataset`'s name.

2022-02-11 12:20 UTC, abowloflrf commented
> > > Thanks for reporting and fixing this bug!
> > > I think there are still some similar mistakes in `implement.go` too, would you like also fix that?
> > 
> > 
> > OK I'll check and fix that.
> > BTW, I noticed that you suggest to change the `NamespacedName` in the `ctx`. Should I change it to `Dataload`'s name or keep as the `Dataset`'s name? Which should be better?
> 
> Sorry to give an improper suggestion at first. After then I double checked the code and found the `ctx` will be used somewhere else(for example, [here](https://github.com/fluid-cloudnative/fluid/blob/master/pkg/controllers/v1alpha1/dataload/dataload_controller.go#L157)), and it requires `ctx.Name` should be `Dataset`'s name. So I think it's better to keep it as the `Dataset`'s name.

👌

2022-02-12 04:52 UTC, TrafalgarZZZ approved these changes

2022-02-12 07:08 UTC, merged