hcfs addresses injector
fluid-cloudnative/fluid pull request #1441
Opened 2022-02-14 07:28 UTC by yangyuliufeng

Signed-off-by: yangyuliufeng <qlw705706@gmail.com>

### Ⅰ. Describe what this PR does
This PR is a part of Bigdata integration optimization. For more details, please visit [the design doc](https://docs.google.com/document/d/1UYpvQAEhDL7t9W1Gr4-QRYIuDMlZXREgQxjfuregzPQ/edit)

The whole job will have three PR:
* this PR
* Shared directory to achieve short-circuit read and write
* Inject jar to help users visit dataset

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2022-02-17 06:49 UTC, xieydd commented
@yangyuliufeng Left some comment on the google doc.

2022-06-06 09:58 UTC, cheyang commented on docs/en/samples/accelerate_data_accessing_by_hdfs.md
> +    metadata:
In Fluid, we are using labels instead of annoations.

2022-06-06 10:02 UTC, cheyang requested changes

2022-06-06 10:02 UTC, cheyang commented on pkg/webhook/plugins/requirenodewithfuse/require_node_with_fuse.go
> +		if runtime.IsHcfsUsed() {
I think whether using hcfs can be determined in pod label instead of runtimeInfo.

2022-06-06 10:04 UTC, cheyang commented on pkg/ddc/base/runtime.go
> +		runtimeInfo, _ = BuildRuntimeInfo(name, namespace, common.UnknownRuntime, datav1alpha1.TieredStore{})
May I know the reason of building runtimeInfo when err is found?

2022-07-08 04:25 UTC, closed without merging