add license info to pkg/ddc/goosefs/transform_hadoop_config.go
fluid-cloudnative/fluid pull request #1564
Opened 2022-03-22 00:58 UTC by kevin999wang

Signed-off-by: kevin999wang 191220111@smail.nju.edu.cn

### Ⅰ. Describe what this PR does
This PR is to add license info to pkg/ddc/goosefs/transform_hadoop_config.go.

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2022-03-22 11:43 UTC, TrafalgarZZZ requested changes

2022-03-22 11:43 UTC, TrafalgarZZZ commented on pkg/ddc/goosefs/transform_hadoop_config.go
> +/*
Please follow the license header sample [here](https://github.com/fluid-cloudnative/fluid/blob/master/pkg/ddc/base/interface.go#L1-L15) to add empty lines.

2022-03-22 13:33 UTC, kevin999wang commented
Got it, fixed, the license info has been regulated.

2022-03-23 15:04 UTC, TrafalgarZZZ approved these changes
LGTM😄

2022-03-23 15:04 UTC, merged