add license information in pkg/ddc/goosefs/operations/base.go
fluid-cloudnative/fluid pull request #1570
Opened 2022-03-22 07:15 UTC by xingshangyu

### Ⅰ. Describe what this PR does
This pr is to add license information in pkg/ddc/goosefs/operations/base.go.

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2022-03-22 11:44 UTC, TrafalgarZZZ approved these changes
LGTM

2022-03-22 11:45 UTC, TrafalgarZZZ requested changes
Please fix DCO using `git commit -s -m "<commit_message>"`

2022-03-23 15:07 UTC, TrafalgarZZZ commented
@xingshangyu Hi, DCO checks all the commits in this PR, the first commit `c09a96e` has no signoff so it still fails. Maybe u should try force-push to override your branch.

2022-03-25 06:11 UTC, cheyang approved these changes

2022-03-25 06:12 UTC, merged