Task128, pkg/ddc/jindo/utils.go
fluid-cloudnative/fluid pull request #1675
Opened 2022-03-29 08:23 UTC by Nash-0110

Signed-off-by: neo <840364310@qq.com>

### Ⅰ. Describe what this PR does
This pr is to add Apache License information in pkg/ddc/jindo/utils.go

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2022-03-31 06:15 UTC, TrafalgarZZZ requested changes

2022-03-31 06:15 UTC, TrafalgarZZZ commented on pkg/ddc/jindo/utils.go
> +
Please delete these two empty lines

2022-03-31 06:24 UTC, Nash-0110 commented on pkg/ddc/jindo/utils.go
> +
Two empty lines have been deleted

2022-04-01 02:46 UTC, cheyang approved these changes

2022-04-03 03:10 UTC, merged