Leverage init container to support non-root scenario, Not Test Yet
fluid-cloudnative/fluid pull request #168
Opened 2020-09-16 16:36 UTC by xieydd

### Ⅰ. Describe what this PR does
Leverage init container to support non-root scenario, Not Test Yet
### Ⅱ. Does this pull request fix one issue?
 fixes #167 
### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.
Add Unit Test for function getPasswdPath getGroupPath getCreateArgs

### Ⅳ. Describe how to verify it
Later

### Ⅴ. Special notes for reviews
@cheyang

2020-09-17 00:04 UTC, cheyang requested changes

2020-09-17 00:04 UTC, cheyang commented on charts/alluxio/values.yaml
> +createImage: xieydd/centos
user creator?

2020-09-17 00:04 UTC, cheyang commented on pkg/ddc/alluxio/utils.go
> +	timestamp := time.Now().Format("20060102150405")
user Path和group path的时间戳可以保持一致。另外是否可以考虑/tmp/fluid_202009150718/作为父文件夹

2020-09-17 00:04 UTC, cheyang commented on pkg/ddc/alluxio/utils.go
> +	logrus.Infoln("User told me to generate passwd file in ", passwd)
这里使用的日志系统不是logrus, kubebuilder
内置的日志系统是"github.com/go-logr/logr"

2020-09-17 00:19 UTC, cheyang requested changes

2020-09-17 00:19 UTC, cheyang commented on Dockerfile.centos
> +FROM centos:latest
建议使用alpine:3.10.2

2020-09-17 00:19 UTC, cheyang commented on go.mod
> +	github.com/sirupsen/logrus v1.4.2
使用已有日志系统，谢谢。

2020-09-17 00:19 UTC, cheyang commented on entrypoint.sh
> +function printUsage {
是否可以考虑环境变量，而不是参数？只是建议哈，可以借鉴https://github.com/Alluxio/alluxio/blob/master/integration/docker/entrypoint.sh#L148-L163

2020-09-17 00:19 UTC, cheyang commented on pkg/ddc/alluxio/types.go
> +	passwdPath string `yaml:"passwdpath"`
变量名passwdPath，groupPath应该是大写，否则反射会失败。

2020-09-17 00:21 UTC, cheyang commented on charts/alluxio/values.yaml
> +createImage: xieydd/centos
是否可以考虑
```
initUsers:
   image: xieydd/centos
  uid: 1005
  gid: 1005
```

2020-09-17 00:28 UTC, cheyang commented
/hold

2020-09-18 03:26 UTC, xieydd commented on charts/alluxio/values.yaml
> +createImage: xieydd/centos
Done

2020-09-18 03:27 UTC, xieydd commented on pkg/ddc/alluxio/utils.go
> +	logrus.Infoln("User told me to generate passwd file in ", passwd)
Done

2020-09-18 03:27 UTC, xieydd commented on go.mod
> +	github.com/sirupsen/logrus v1.4.2
Done

2020-09-18 03:27 UTC, xieydd commented on pkg/ddc/alluxio/types.go
> +	passwdPath string `yaml:"passwdpath"`
Done

2020-09-18 06:41 UTC, merged