Add faq(zh)
fluid-cloudnative/fluid pull request #177
Opened 2020-09-21 07:59 UTC by iluoeli

### Ⅰ. Describe what this PR does
Add docs for FAQ

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2020-09-21 09:29 UTC, cheyang requested changes

2020-09-21 09:29 UTC, cheyang commented on docs/zh/userguide/faq.md
> +## 为什么我无法删除Runtime？
首先加个序号，我们知道有几个Q&A

2020-09-21 09:29 UTC, cheyang requested changes

2020-09-21 09:29 UTC, cheyang commented on docs/zh/userguide/faq.md
> +只要有任何活跃Pod还在使用Fluid创建的Volume，Fluid就不会完成删除操作。
能否提供工具帮助用户快速排查？

2020-09-22 05:56 UTC, iluoeli commented on docs/zh/userguide/faq.md
> +## 为什么我无法删除Runtime？
done

2020-09-22 05:58 UTC, iluoeli commented on docs/zh/userguide/faq.md
> +只要有任何活跃Pod还在使用Fluid创建的Volume，Fluid就不会完成删除操作。
这个查看pvc就可以看到使用的pod了。
我提供了一条命令找出活跃Pod：
```bash
kubectl describe pvc nested-imagenet -n default | \
	awk '/^Mounted/ {flag=1}; /^Events/ {flag=0}; flag' | \
	awk 'NR==1 {print $3}; NR!=1 {print $1}' | \
	xargs -I {} kubectl get po {} | \
	grep -E "Running|Terminating|Pending" | \
	cut -d " " -f 1
```

2020-09-22 11:48 UTC, cheyang commented
感觉修改的文件有点多，哪里出了问题？

2020-09-22 11:49 UTC, iluoeli commented
> 感觉修改的文件有点多，哪里出了问题？

其他文件的换行符不对，我顺便格式化为LF了

2020-09-23 01:05 UTC, cheyang requested changes

2020-09-23 01:05 UTC, cheyang commented on docs/zh/userguide/faq.md
> +只要有任何活跃Pod还在使用Fluid创建的Volume，Fluid就不会完成删除操作。
这个加到文档里了吗？

2020-09-23 08:05 UTC, merged