Add jindofsx fuseOnly deploy mode
fluid-cloudnative/fluid pull request #1809
Opened 2022-04-26 12:12 UTC by frankleaf

Signed-off-by: frankleaf <frank.wt@alibaba-inc.com>

### Ⅰ. Describe what this PR does

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2022-04-27 02:29 UTC, cheyang requested changes

2022-04-27 02:29 UTC, cheyang commented on api/v1alpha1/jindoruntime_types.go
> +	DISABLE bool `json:"disable,omitempty"`
DISABLE -> Disabled, disable -> disabled

2022-04-27 02:29 UTC, cheyang commented on charts/fluid/fluid/crds/data.fluid.io_jindoruntimes.yaml
> +    controller-gen.kubebuilder.io/version: v0.7.0
Please upgrade controller-gen

2022-04-27 03:14 UTC, frankleaf commented on api/v1alpha1/jindoruntime_types.go
> +	DISABLE bool `json:"disable,omitempty"`
done

2022-04-27 03:14 UTC, frankleaf commented on charts/fluid/fluid/crds/data.fluid.io_jindoruntimes.yaml
> +    controller-gen.kubebuilder.io/version: v0.7.0
done

2022-04-27 07:24 UTC, cheyang commented on pkg/ddc/jindofsx/const.go
> +	FUSE_ONLY = "fuseOnly"
这里的变量名应该是FuseOnly。

2022-04-27 07:27 UTC, cheyang requested changes

2022-04-27 07:27 UTC, cheyang commented on pkg/ddc/jindofsx/health_check.go
>  	err = e.checkMasterHealthy()
我觉得逻辑上应该是：

```golang
if !e.runtime.Spec.Master.Disabled{
err = e.checkMasterHealthy()
if err != nil {

    
          
            
    

          
    
    
  
		e.Log.Error(err, "The master is not healthy")
		updateErr := e.UpdateDatasetStatus(data.FailedDatasetPhase)
		if updateErr != nil {
			e.Log.Error(updateErr, "Failed to update dataset")
		}
		return
	}
}
```

2022-04-27 07:30 UTC, cheyang requested changes

2022-04-27 07:30 UTC, cheyang commented on pkg/ddc/jindofsx/ufs.go
> +		err = nil
这里直接 return就好，默认err就是nil

2022-04-27 07:38 UTC, cheyang commented on pkg/ddc/jindofsx/master.go
> +		return
直接用 return true, nil

2022-04-27 14:28 UTC, zwwhdls approved these changes

2022-04-28 02:25 UTC, cheyang approved these changes

2022-04-28 02:25 UTC, merged