Support allow_root fuse option for non-root user
fluid-cloudnative/fluid pull request #194
Opened 2020-09-25 13:11 UTC by TrafalgarZZZ

### Ⅰ. Describe what this PR does
Support allow_root fuse option for non-root user

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2020-09-25 15:24 UTC, cheyang requested changes

2020-09-25 15:24 UTC, cheyang commented on charts/alluxio/templates/fuse/daemonset.yaml
> +              mountPropagation: Bidirectional
mountPropagation: Bidirectional 为什么必须要加？

2020-09-25 15:24 UTC, cheyang commented on charts/alluxio/templates/fuse/daemonset.yaml
> +            runAsGroup: {{ .Values.fuse.group }}
是否可以简化成.Values.user ？

2020-09-25 15:24 UTC, cheyang commented on samples/ufspath/dataset.yaml
> +    imageTag: 2.3.0-SNAPSHOT-f0b220e-nonroot
我构建一个最新的镜像，我们把内置的镜像也替换掉吧。

2020-09-26 03:11 UTC, TrafalgarZZZ commented on samples/ufspath/dataset.yaml
> +    imageTag: 2.3.0-SNAPSHOT-f0b220e-nonroot
done

2020-09-26 03:11 UTC, TrafalgarZZZ commented on charts/alluxio/templates/fuse/daemonset.yaml
> +            runAsGroup: {{ .Values.fuse.group }}
done

2020-09-26 03:12 UTC, TrafalgarZZZ commented on charts/alluxio/templates/fuse/daemonset.yaml
> +              mountPropagation: Bidirectional
不需要加，已经去除

2020-09-26 06:40 UTC, cheyang commented
/lgtm

2020-09-26 06:40 UTC, merged