Update demo docs
fluid-cloudnative/fluid pull request #198
Opened 2020-09-27 11:43 UTC by TrafalgarZZZ

### Ⅰ. Describe what this PR does
Update demo docs:
- Update demo doc "accelerate data accessing"
- Update demo doc "data co-locality"
- Add demo doc "guide for non-root users"
- Update related samples
- Update TOC

### Ⅱ. Does this pull request fix one issue?

fixes #185 

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews
`hostpath.md` should also be updated. Working on it

2020-09-27 15:39 UTC, cheyang requested changes

2020-09-27 15:39 UTC, cheyang commented on docs/zh/samples/nonroot_access.md
> +# 示例 - 以non-root用户身份使用Fluid
是不是应该改成 使用Fluid访问非root用户的数据

2020-09-27 15:39 UTC, cheyang commented on docs/zh/samples/nonroot_access.md
> +在使用Fluid时，用户不必拥有root权限即可创建Dataset，将自己的数据集挂载到Fluid上，并创建相关应用消费这些数据
如果用户的数据只能以特定uid访问时，需要通过设置Runtime的RunAs参数指定特定用户运行Cache Engine访问底层数据。

2020-09-28 02:20 UTC, TrafalgarZZZ commented on docs/zh/samples/nonroot_access.md
> +在使用Fluid时，用户不必拥有root权限即可创建Dataset，将自己的数据集挂载到Fluid上，并创建相关应用消费这些数据
感谢建议 已修改

2020-09-28 02:21 UTC, TrafalgarZZZ commented on docs/zh/samples/nonroot_access.md
> +# 示例 - 以non-root用户身份使用Fluid
已修改

2020-09-28 08:41 UTC, cheyang commented
/lgtm

2020-09-28 08:41 UTC, merged