[FEATURES] Support deploy multiple Dataset in the same node
fluid-cloudnative/fluid pull request #242
Opened 2020-10-19 09:46 UTC by xieydd

### Ⅰ. Describe what this PR does

[FEATURES] Deploy multiple Dataset in the same node 
### Ⅱ. Does this pull request fix one issue?

#218 #147 

### Ⅴ. Special notes for reviews
@cheyang @apc999

2020-10-19 10:18 UTC, cheyang requested changes

2020-10-19 10:18 UTC, cheyang commented on pkg/ddc/alluxio/types.go
> +	path = "/dev/shm/default/default"
能否补齐namespace和name呢，另外Path目录需要补齐namespace/name

2020-10-19 10:18 UTC, cheyang commented on pkg/ddc/alluxio/utils.go
> +	passwd := fmt.Sprintf("/tmp/%s/%s/%s_passwd", e.namespace, e.name, timestamp)
是否还需要timestamp？

2020-10-19 10:18 UTC, cheyang commented on pkg/ddc/alluxio/utils.go
> +	group := fmt.Sprintf("/tmp/%s/%s/%s_group", e.namespace, e.name, timestamp)
是否还需要timestamp？

2020-10-19 10:18 UTC, cheyang commented on pkg/ddc/alluxio/utils.go
> +	passwd := fmt.Sprintf("/tmp/%s/%s/%s_passwd", e.namespace, e.name, timestamp)
只是好奇？为什么还需要timestamp

2020-10-19 10:18 UTC, cheyang commented on pkg/ddc/alluxio/utils.go
> +	// pod not assigned
能否迁移到github.com/fluid-cloudnative/fluid/pkg/utils/kubeclient/pod.go

2020-10-19 10:18 UTC, cheyang commented on pkg/ddc/alluxio/utils.go
> +func (e *AlluxioEngine) getK8sClusterUsedPort() ([]int, error) {
这个方法看起来更像是工具方法。

2020-10-19 10:20 UTC, cheyang requested changes

2020-10-19 10:20 UTC, cheyang commented on charts/alluxio/templates/config/alluxio-conf.yaml
> +  ALLUXIO_WORKER_TIEREDSTORE_LEVEL0_DIRS_PATH: "${ALLUXIO_WORKER_TIEREDSTORE_LEVEL0_DIRS_PATH}"
这个很有可能不用改

2020-10-19 10:28 UTC, xieydd commented on pkg/ddc/alluxio/utils.go
> +	passwd := fmt.Sprintf("/tmp/%s/%s/%s_passwd", e.namespace, e.name, timestamp)
应该不需要 timestamp 了

2020-10-19 10:29 UTC, xieydd commented on charts/alluxio/templates/config/alluxio-conf.yaml
> +  ALLUXIO_WORKER_TIEREDSTORE_LEVEL0_DIRS_PATH: "${ALLUXIO_WORKER_TIEREDSTORE_LEVEL0_DIRS_PATH}"
嗯，应该会被环境变量覆盖

2020-10-19 10:57 UTC, xieydd commented on pkg/ddc/alluxio/utils.go
> +	// pod not assigned
Done

2020-10-19 11:13 UTC, xieydd commented on pkg/ddc/alluxio/utils.go
> +func (e *AlluxioEngine) getK8sClusterUsedPort() ([]int, error) {
ok, 更新到工具方法

2020-10-19 11:16 UTC, xieydd commented on pkg/ddc/alluxio/types.go
> +	path = "/dev/shm/default/default"
Done

2020-10-19 11:19 UTC, xieydd commented on pkg/ddc/alluxio/transform.go
> +	err := e.getAvaliablePort()
想着是否会复用，可以先改成临时变量

2020-10-21 07:04 UTC, cheyang commented on pkg/ddc/alluxio/metadata.go
> +			fileUtils := operations.NewAlluxioFileUtils(podName, containerName, e.namespace, e.Log, e.Properties)
这个properties是不是必须的？这些应该都是Alluxio的集群级别properties。

2020-10-21 07:28 UTC, cheyang commented on charts/alluxio/templates/config/alluxio-conf.yaml
> +{{- $masterJavaOpts = printf "-Dalluxio.master.rpc.port=%v" .Values.master.ports.rpc | append $masterJavaOpts }}
是不是配置到alluxioJavaOpts这个变量中会更合适一些。甚至我在想这个是否可以放到properties中，这样可以比较容易和Alluxio线上的chart保持一致，要不差异化有点大了。

2020-10-21 07:28 UTC, cheyang commented on pkg/ddc/alluxio/engine.go
> +	Properties             []string
这里的properties都是些什么参数呢？

2020-10-21 08:03 UTC, cheyang commented on charts/alluxio/templates/master/statefulset.yaml
> +        command: ["alluxio","formatJournal","{{ $masterPorts }}"]
这个命令不能智能判断master的rpc port吗？

2020-10-21 08:03 UTC, cheyang commented on pkg/ddc/alluxio/node.go
> +	// if e.alreadyAssignedByFluid(node) {
可以加个todo，是否需要考虑资源使用？还是在其他阶段考虑资源使用。

2020-10-21 08:37 UTC, cheyang commented on charts/alluxio/values.yaml
> +  enabled: true
应该改为false

2020-10-21 08:37 UTC, cheyang commented on charts/alluxio/values.yaml
> +  dir: "/tmp/fluid/default/dataset"
dir: ""

2020-10-21 09:49 UTC, cheyang commented
/hold

2020-10-21 11:04 UTC, cheyang requested changes

2020-10-21 11:04 UTC, cheyang commented on pkg/ddc/alluxio/transform_optimization.go
> +	setDefaultProperties(runtime, value, "alluxio.master.rpc.port", strconv.Itoa(value.Master.Ports.Rpc))
建议单独定义一个方法做Port设置

2020-10-21 12:02 UTC, cheyang commented on pkg/ddc/alluxio/transform_optimization.go
> +func (e *AlluxioEngine) setPortProperties(runtime *datav1alpha1.AlluxioRuntime, value *Alluxio) {
这个方法是被谁调用的？

2020-10-21 12:05 UTC, xieydd commented on pkg/ddc/alluxio/transform_optimization.go
> +func (e *AlluxioEngine) setPortProperties(runtime *datav1alpha1.AlluxioRuntime, value *Alluxio) {
Done

2020-10-21 13:15 UTC, merged

2020-10-21 13:15 UTC, cheyang reviewed
/approve