testcase: add testcase 12
fluid-cloudnative/fluid pull request #2429
Opened 2022-12-14 07:02 UTC by wang-mask

### Ⅰ. Describe what this PR does
testcase: 12 - CSI Plugin Stale Node Patch

### Ⅱ. Does this pull request fix one issue?

add testcase-12 in https://github.com/fluid-cloudnative/community/blob/master/testcase/fluid-testcase.md

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2022-12-15 04:19 UTC, cheyang commented on test/prow/csi_stable_patch.py
> +    main()
Add return of line.

2022-12-15 09:10 UTC, TrafalgarZZZ requested changes

2022-12-15 09:10 UTC, TrafalgarZZZ commented on test/prow/csi_stable_patch.py
> +    config.load_kube_config()
Please change it to `config.load_incluster_config()`

2022-12-16 06:01 UTC, TrafalgarZZZ commented
/test fluid-e2e

2022-12-17 01:53 UTC, wang-mask commented
> /test fluid-e2e

what？

2022-12-17 04:45 UTC, cheyang commented
/test fluid-e2e

2022-12-19 01:38 UTC, cheyang commented
/lgtm
/approve

2022-12-19 01:39 UTC, merged