Add multi dataset in same node Doc
fluid-cloudnative/fluid pull request #254
Opened 2020-10-22 06:25 UTC by xieydd

### Ⅰ. Describe what this PR does
Add multi dataset in same node Doc
### Ⅱ. Does this pull request fix one issue?

#248 
### Ⅴ. Special notes for reviews
@cheyang

2020-10-22 07:57 UTC, cheyang requested changes

2020-10-22 07:57 UTC, cheyang commented on docs/zh/samples/multi_dataset_same_node_accessing.md
> +    - mountPoint: http://dl.unisound.ai/atlas/lustre-fs/lustre-server-latest/
这个网站，读者应该没办法访问。

2020-10-22 11:08 UTC, xieydd commented on docs/zh/samples/multi_dataset_same_node_accessing.md
> +    - mountPoint: http://dl.unisound.ai/atlas/lustre-fs/lustre-server-latest/
done

2020-10-22 12:01 UTC, cheyang commented on docs/en/userguide/get_started.md
> +        - mountPoint: https://mirror.bit.edu.cn/apache/spark/spark-3.0.1/
如果换成https://mirror.bit.edu.cn/apache/spark/是否可以，我担心这个不断更新，我们的文档也需要保持变化？

2020-10-22 12:03 UTC, cheyang commented on docs/zh/samples/multi_dataset_same_node_accessing.md
> +    - mountPoint: https://mirrors.tuna.tsinghua.edu.cn/apache/hbase/2.2.5/
是否可以用：https://downloads.apache.org/hbase/stable/？

2020-10-22 12:12 UTC, xieydd commented on docs/en/userguide/get_started.md
> +        - mountPoint: https://mirror.bit.edu.cn/apache/spark/spark-3.0.1/
可行

2020-10-22 12:13 UTC, xieydd commented on docs/zh/samples/multi_dataset_same_node_accessing.md
> +    - mountPoint: https://mirrors.tuna.tsinghua.edu.cn/apache/hbase/2.2.5/
嗯 https://downloads.apache.org/hbase/stable/ 可行

2020-10-22 13:43 UTC, cheyang commented on docs/zh/samples/multi_dataset_same_node_accessing.md
> +**查看Service查看Port分配情况**
这个细节对于用户暴露的原因？用户可能会迷惑。

2020-10-22 13:51 UTC, xieydd commented on docs/zh/samples/multi_dataset_same_node_accessing.md
> +**查看Service查看Port分配情况**
对用户来说可能没有太大用处，我去掉。

2020-10-23 02:31 UTC, cheyang approved these changes

2020-10-23 02:31 UTC, merged