split dataset controller and alluxioruntime controller, edit makefile…
fluid-cloudnative/fluid pull request #271
Opened 2020-10-26 14:54 UTC by yangyuliufeng

### Ⅰ. Describe what this PR does
This PR split the runtime_controller into dataset_controller and alluxioruntime_controller.
I have edited the makefile and dockerfile about buinding images for dataset_controller and alluxioruntime_controller.
In my last PR, I printed version log by "glog" package when csi starting in version.go. I habe changed it to "log" package because it seems like that glog.infof will conflict with setupLog in controller.
I have reduce the authority of dataset_controller and alluxioruntime_controller. They used the role of cluster-admin before.
### Ⅱ. Does this pull request fix one issue?

fixes #100

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.
I have tested it by "make docker-build-all" and testing part of cases.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews
The image address in chart v4 need to be edited.

2020-10-26 15:50 UTC, cheyang requested changes

2020-10-26 15:50 UTC, cheyang commented on Dockerfile.dataset
> +CMD dataset-controller start
加一个回车符

2020-10-26 15:50 UTC, cheyang commented on cmd/alluxioruntime_controller/main.go
> +		LeaderElectionID:   "7857424864.data.fluid.io",
为什么要加leaderElectionID？另外MaxConcurrentReconciles删除的原因是什么呢？

2020-10-26 15:50 UTC, cheyang commented on charts/fluid/v0.4.0/values.yaml
> +controller:
名字改成下面这样如何？

```
dataset:
    controller:
```

2020-10-26 16:08 UTC, cheyang commented on cmd/dataset_controller/main.go
> +		LeaderElectionID:   "89759796.data.fluid.io",
需要LeaderElectionID吗？

2020-10-27 00:05 UTC, cheyang requested changes
非常感谢，总体很赞！

1.请修复下CI中的问题：https://travis-ci.org/github/fluid-cloudnative/fluid/jobs/738993270
2.v0.4.0的helm chart等发布后再做snapshot，我们还是在chart/fluid/fluid下修改吧
3.有些小问题，我们可以讨论

2020-10-27 01:21 UTC, yangyuliufeng commented on cmd/alluxioruntime_controller/main.go
> +		LeaderElectionID:   "7857424864.data.fluid.io",
leaderElectionID是选主的时候configMapsResourceLock的分布式锁的名字。manager.Options里并没有这个字段MaxConcurrentReconciles。

2020-10-27 02:36 UTC, cheyang commented on cmd/alluxioruntime_controller/main.go
> +		LeaderElectionID:   "7857424864.data.fluid.io",
MaxConcurrentReconciles 是在这里定义的，后面我们可以加上 https://github.com/kubernetes-sigs/controller-runtime/issues/964

2020-10-27 02:54 UTC, cheyang approved these changes

2020-10-27 03:06 UTC, merged