Remove redundant comment task2
fluid-cloudnative/fluid pull request #298
Opened 2020-10-30 12:54 UTC by ConnyLamp

### Ⅰ. Describe what this PR does
Remove remove redundant comment on GenerateHelmTemplate function.(pkg/utils/helm/helm.go)

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2020-10-30 15:35 UTC, cheyang commented
Please create an issue on it. Thanks.

2020-10-31 03:49 UTC, xieydd reviewed
How about add space after `//`

2020-10-31 03:51 UTC, cheyang requested changes

2020-10-31 03:51 UTC, cheyang commented on pkg/utils/helm/helm.go
> +//GenerateHelmTemplate generates helm template without tiller: helm template -f values.yaml chart_name
Thanks for the suggestions from @xieydd . 
Please add space between '//' and content. Just like "// GenerateHelmTemplate"

2020-11-03 12:32 UTC, cheyang approved these changes

2020-11-03 12:32 UTC, merged