change the first word of the comment to the function name
fluid-cloudnative/fluid pull request #305
Opened 2020-10-31 09:14 UTC by fly923

In this comment normalization, l change the first word of the comment to the function name. Lowercase the first letter of the word 'Check'. And add a period at the end of the comment.

2020-10-31 09:55 UTC, xieydd reviewed
Could you open an issue on it and relate it to the PR. And you can make the comment more detailed, Thanks.

2020-11-01 15:10 UTC, cheyang requested changes
Could you open an issue on it and relate it to the PR. And you can make the comment more detailed, Thanks.

check -> checks

2020-11-05 09:31 UTC, cheyang commented
@fly923 could you please update your PR according to the comments？

2020-11-14 15:05 UTC, cheyang approved these changes

2020-11-14 15:05 UTC, merged