Normalized comment on ListAllReleasesWithDetail  Fixes #312
fluid-cloudnative/fluid pull request #313
Opened 2020-11-01 10:42 UTC by 1250658183

### Ⅰ. Describe what this PR does
Normalize comments on func ListAllReleasesWithDetail (pkg/utils/helm/utils.go)

### Ⅱ. Does this pull request fix one issue?

fixes #312 

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2020-11-01 15:06 UTC, cheyang requested changes

2020-11-01 15:06 UTC, cheyang commented on pkg/utils/helm/utils.go
> +// ListAllReleasesWithDetail return a map with all releases' names and other info in a given namespace
return -> returns

2020-11-01 15:10 UTC, 1250658183 commented on pkg/utils/helm/utils.go
> +// ListAllReleasesWithDetail return a map with all releases' names and other info in a given namespace
Sorry, I will fix it immediately

2020-11-02 03:10 UTC, cheyang approved these changes

2020-11-02 03:10 UTC, cheyang commented
@1250658183 thanks for your contributions!

2020-11-02 03:10 UTC, merged