normalize the annotation method DeleteReleaseIfExists in pkg/utils/hel…
fluid-cloudnative/fluid pull request #317
Opened 2020-11-02 12:38 UTC by onceicy

…m/utils.go

### Ⅰ. Describe what this PR does
It normalizes the annotation method DeleteReleaseIfExists in pkg/utils/helm/utils.go.

### Ⅱ. Does this pull request fix one issue?

Fixes #316 

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2020-11-02 15:19 UTC, TrafalgarZZZ requested changes

2020-11-02 15:19 UTC, TrafalgarZZZ commented on pkg/utils/helm/utils.go
> +//A wrapper of CheckRelease() and DeleteRelease()
Please add a space before each comment line and change "delete" to "deletes"

2020-11-03 12:35 UTC, cheyang requested changes

2020-11-03 12:35 UTC, cheyang commented on pkg/utils/helm/utils.go
> +
Please add space between '//' and 'DeleteReleaseIfExists'

2020-11-05 11:01 UTC, cheyang approved these changes

2020-11-05 11:01 UTC, merged