build alluxio docker image
fluid-cloudnative/fluid pull request #358
Opened 2020-11-07 09:47 UTC by cheyang

### Ⅰ. Describe what this PR does

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2020-11-07 16:02 UTC, TrafalgarZZZ requested changes

2020-11-07 16:02 UTC, TrafalgarZZZ commented on tools/alluxio/build-image.sh
> +  docker exec -it ${dev_container_name} /bin/bash -c "sh /tarball.sh"
是不是该把`tarball.sh`也迁移过来，或者将它内嵌在该脚本里？

2020-11-08 04:11 UTC, cheyang commented on tools/alluxio/build-image.sh
> +  docker exec -it ${dev_container_name} /bin/bash -c "sh /tarball.sh"
谢谢，已经更新。

2020-11-08 06:07 UTC, TrafalgarZZZ approved these changes

2020-11-08 14:35 UTC, merged