remove kubectl for runtime and dataset controller
fluid-cloudnative/fluid pull request #3716
Opened 2024-02-06 03:27 UTC by xliuqq

### Ⅰ. Describe what this PR does
Remove kubectl shell command usage for runtime and dataset controller, use client go instead.

### Ⅱ. Does this pull request fix one issue?

fixes #XXXX

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it
existed e2e tests.

### Ⅴ. Special notes for reviews

2024-02-06 07:27 UTC, cheyang requested changes

2024-02-06 07:27 UTC, cheyang commented on pkg/utils/kubeclient/configmap.go
> +
I think it's better to use this way:

```golang
return client.Create(context.TODO(), configMap)
```

2024-02-06 07:47 UTC, xliuqq commented on pkg/utils/kubeclient/configmap.go
> +
ok.

2024-02-06 08:15 UTC, cheyang commented
I suggest keeping pkg/utils/kubectl/configmap.go in this PR. We can deprecate it in later PR.

2024-02-08 02:50 UTC, TrafalgarZZZ commented
/test fluid-e2e
/lgtm

2024-02-08 03:37 UTC, TrafalgarZZZ commented
/retest

2024-02-08 05:56 UTC, cheyang approved these changes
/lgtm
/approve

2024-02-08 05:57 UTC, cheyang commented
/test fluid-e2e

2024-02-08 05:58 UTC, cheyang approved these changes
/lgtm
/approve

2024-02-08 06:53 UTC, merged