support to set the image name
fluid-cloudnative/fluid pull request #388
Opened 2020-11-19 12:50 UTC by XIAO-HOU

### Ⅰ. Describe what this PR does
update the script so that users can set their own image names and push images to their own repositoris. 

### Ⅱ. Does this pull request fix one issue?

fixes #340 
### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify

### Ⅴ. Special notes for reviews

2020-11-20 00:58 UTC, cheyang requested changes

2020-11-20 00:58 UTC, cheyang commented on tools/alluxio/build-image.sh
> +{
如果没有设置镜像，是否可以使用默认镜像？

2020-11-20 00:59 UTC, cheyang commented
请更新一下文档，帮助用户理解如何使用该脚本。

2020-11-20 01:00 UTC, XIAO-HOU commented on tools/alluxio/build-image.sh
> +{
不可以，会提示让你重新输入命令带上镜像名字，这个要改吗

2020-11-21 08:06 UTC, cheyang approved these changes

2020-11-21 08:06 UTC, merged