Normalized the comment of func TotalFileNums
fluid-cloudnative/fluid pull request #391
Opened 2020-11-20 05:40 UTC by zhouqbuuu

### Ⅰ. Describe what this PR does
I normalized the comment of func TotalFileNums in pkg/ddc/alluxio/ufs.go

### Ⅱ. Does this pull request fix one issue?
fixes #389 

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2020-11-20 06:57 UTC, cheyang requested changes

2020-11-20 06:57 UTC, cheyang commented on pkg/ddc/alluxio/ufs.go
> +// TotalFileNums return the total num of files in Alluxio
return -> returns

2020-11-25 10:04 UTC, zhouqbuuu commented on pkg/ddc/alluxio/ufs.go
> +// TotalFileNums return the total num of files in Alluxio
I've already changed it

2020-11-29 16:11 UTC, xieydd approved these changes

2020-11-29 23:44 UTC, cheyang approved these changes

2020-11-29 23:44 UTC, merged