edit nodeplugin to support more runtime
fluid-cloudnative/fluid pull request #398
Opened 2020-11-25 01:27 UTC by yangyuliufeng

### Ⅰ. Describe what this PR does
set the mount root of runtime as /runtime-mnt
change the mount path of alluxioruntime to /runtime-mnt/alluxio
developer of runtime can set the supporting mount type of csiplugin by editing the env in the form of "fuse.alluxio-fuse,fuse.jindofs-fuse,......"

### Ⅱ. Does this pull request fix one issue?

fixes #397 

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it
I have vertified it in testing environment.
### Ⅴ. Special notes for reviews

2020-11-25 06:15 UTC, cheyang requested changes

2020-11-25 06:15 UTC, cheyang commented on charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
> +          {{- if .Values.runtime.alluxio.mountSubpath }}
该部分是否可以不修改？

2020-11-25 06:15 UTC, cheyang commented on pkg/csi/fuse/utils.go
> +	args := []string{fluidPath, strings.Replace(mountType, ",", "|", -1)}
我建议可以通过VolumeAttributes传入fuse_type， 比如alluxio是mount_type: fuse.alluxio-fuse

https://github.com/fluid-cloudnative/fluid/blob/master/pkg/ddc/alluxio/create_volume.go#L110

2020-11-25 06:15 UTC, cheyang commented on pkg/csi/fuse/utils.go
> +	args := []string{fluidPath, strings.Replace(mountType, ",", "|", -1)}
这样我们就不需要额外配置环境变量FUSE_TYPE

2020-11-25 06:18 UTC, cheyang commented
有两个建议：

1. 不需要单独MOUNT_TYPE环境变量， 可以通过VolumeAttributes传入fuse_type， 比如alluxio是mount_type: fuse.alluxio-fuse

https://github.com/fluid-cloudnative/fluid/blob/master/pkg/ddc/alluxio/create_volume.go#L110

2. 具体Runtime的实现可以指定RUNTIME类型： https://github.com/fluid-cloudnative/fluid/blob/master/pkg/ddc/alluxio/create_volume.go#L72

```
mountPath := fmt.Sprintf("%s/%s/%s/alluxio-fuse", mountRoot, e.namespace, e.name)
```

可以改为

```
mountPath := fmt.Sprintf("%s/%s/%s/%s/alluxio-fuse", mountRoot, common.ALLUXIO_RUNTIME,e.namespace, e.name)
```

2020-11-25 06:29 UTC, yangyuliufeng commented on charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
> +          {{- if .Values.runtime.alluxio.mountSubpath }}
如果不修改，可以将runtime.alluxio.mountSubpath移除，alluxio程序里那段生成挂载目录位置的代码改一下，改为csi.plugins.mountType+runtimetype。

2020-11-26 00:46 UTC, cheyang requested changes

2020-11-26 00:46 UTC, cheyang commented on charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
> +          {{- if .Values.csi.plugins.mountRoot }}
请问改名的原因？

2020-11-26 00:46 UTC, cheyang commented on pkg/ddc/alluxio/const.go
> +	ALLUXIO_MOUNT = "/alluxio"
和Alluixo相关的变量可以放到alluixo.go文件

2020-11-26 01:21 UTC, cheyang requested changes

2020-11-26 01:21 UTC, cheyang commented on pkg/csi/fuse/nodeserver.go
> +	if mountType == "" {
是否要兼容一下已有环境，默认为alluxio runtime类型。

2020-11-26 07:58 UTC, yangyuliufeng commented on charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
> +          {{- if .Values.csi.plugins.mountRoot }}
因为原来runtime.mountRoot是/alluxio-mnt，是运行时的挂载目录，我觉得现在mountRoot相当于csi.plugins定义的一个mount root，不同运行时在这个mount root下建立子挂载目录。因此mountRoot属性还放在runtime下不妥。

2020-11-26 09:47 UTC, cheyang commented on charts/fluid/fluid/templates/controller/alluxioruntime_controller.yaml
> +          {{- if .Values.csi.plugins.mountRoot }}
是不是只要把value改成/runtime-mnt就好了？

2020-11-27 01:59 UTC, cheyang commented
Thanks very much ! @yangyuliufeng

2020-11-27 02:06 UTC, xieydd approved these changes

2020-11-27 04:29 UTC, merged