This pr is to add the translation of the Apache License notice
fluid-cloudnative/fluid pull request #4078
Opened 2024-05-11 08:33 UTC by zrywby

### Ⅰ. Describe what this PR does

### Ⅱ. Does this pull request fix one issue?

fixes #XXXX

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2024-05-21 08:13 UTC, LiYuhang9527 commented
please add "-s" when you use commande "git commit"

2024-05-31 03:13 UTC, TrafalgarZZZ requested changes

2024-05-31 03:13 UTC, TrafalgarZZZ commented on cmd/thin/app/thin.go
> +
Pls uncomment these lines. They are required for golang to import packages

2024-07-05 02:59 UTC, TrafalgarZZZ approved these changes

2024-07-06 03:44 UTC, merged