fix default value
fluid-cloudnative/fluid pull request #4144
Opened 2024-05-30 11:45 UTC by frankleaf

### Ⅰ. Describe what this PR does

### Ⅱ. Does this pull request fix one issue?

fixes #XXXX

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2024-05-30 12:42 UTC, cheyang commented
@frankleaf Please fix the ut. Thanks.

2024-05-31 07:21 UTC, frankleaf commented
> @frankleaf Please fix the ut. Thanks.
done

2024-06-03 12:55 UTC, cheyang requested changes

2024-06-03 12:55 UTC, cheyang commented on pkg/ddc/jindocache/transform.go
> +		if mount.Options["cacheStrategy"] == "DHT" && metaPolicy == "ONCE" {
There are two checks for mount.Options["cacheStrategy"] == "DHT" in the code. How about using the following way:

```golang
if cacheStrategy := mount.Options["cacheStrategy"]; cacheStrategy == "DHT" {
    if metaPolicy == "ONCE" {
        cacheStrategy = cacheStrategy 
    } else {
        err = fmt.Errorf("CacheStrategy DHT must be used with metaPolicy ONCE and current metaPolicy is %s", metaPolicy)
        e.Log.Error(err, "Incorrect metaPolicy", metaPolicy)
        return err
    }
}
```

2024-06-03 13:03 UTC, cheyang requested changes

2024-06-03 13:03 UTC, cheyang commented on pkg/ddc/jindocache/transform.go
> +		if mount.Options["metaPolicy"] == "ALWAYS" {
For metaPolicy, it only checks for the "ALWAYS" case but not the "ONCE" case. You might want to add a more thorough check.
```golang
if userMetaPolicy, ok := mount.Options["metaPolicy"]; ok {
    if userMetaPolicy == "ONCE" || userMetaPolicy == "ALWAYS" {
         metaPolicy = userMetaPolicy
    } else {
         err = fmt.Errorf("Invalid metaPolicy: %s", userMetaPolicy)
         e.Log.Error(err, "Invalid metaPolicy")
         return err
    }
}
```

2024-06-04 08:14 UTC, cheyang approved these changes
/lgtm
/approve

2024-06-04 08:15 UTC, merged