edit the deleting logic of dataset and alluxioruntime
fluid-cloudnative/fluid pull request #422
Opened 2020-11-30 11:26 UTC by yangyuliufeng

### Ⅰ. Describe what this PR does
This PR edits the deleting logic of dataset and alluxioruntime , so that delete dataset can cascading delete runtime. 
The alluxioruntime needs to query the cache through the dataset when it is deleted. Now , it can be deleted without a dataset.
During the deleting logic, I have found a bug : when deleting alluxioruntime, the pvc can be deleted if the pvc name is not same as the volume name defined in pod.Spec.Volumes
So , I changed the calibration condition from  "if pvc.Name == pvcName" in function GetPvcMountPods to "pvc.PersistentVolumeClaim.ClaimName == pvcName".

### Ⅱ. Does this pull request fix one issue?

#405
#420
### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it
when a pod is using the pvc ,delete the dataset, it cannot be deleted.
When deleting a dataset , the alluxioruntime will be deleted later.
### Ⅴ. Special notes for reviews
the return values in cache.go are not consistent， I change them to  "states".

2020-12-01 09:52 UTC, cheyang requested changes

2020-12-01 09:52 UTC, cheyang commented on pkg/controllers/runtime_controller.go
> +	// 6. Add Finalizer of runtime
Add finalizer是否可以再提前一点？

2020-12-01 12:39 UTC, TrafalgarZZZ requested changes

2020-12-01 12:39 UTC, TrafalgarZZZ commented on pkg/ddc/alluxio/cache.go
> +		e.Log.Info("Failed to get dataset when query cache status")
此处是否对NotFound Error和其他Error分开处理更直观？例如使用`utils.IgnoreNotFound`将NotFound Error忽略掉，`cleanUpCache()`方法中也可以进而修改为对`err != nil`的判断

2020-12-02 13:08 UTC, xieydd commented on pkg/controllers/runtime_controller.go
> +	// 6. Add Finalizer of runtime
正确的逻辑是？：
1. 获取 runtime
2. Add Finalizer of runtime
3. Get the dataset 
4. Get the ObjectMeta of runtime
5. Reconcile delete the runtime
6. update status of dataset

2020-12-02 15:23 UTC, xieydd commented on pkg/controllers/runtime_controller.go
> +// AddFinalizerAndRequeue add  finalizer and requeue
AddOwnerAndRequeue add OwnerReferences for runtime metadata and requeue

2020-12-02 17:02 UTC, yangyuliufeng commented on pkg/controllers/runtime_controller.go
> +	// 6. Add Finalizer of runtime
@xieydd 我觉得应该是
1、获取runtime
2、ReconcileRuntimeDeletion（这个可以放到前面来）
3、Get the ObjectMeta of runtime
4、Get the dataset
5、if dataset exist：
（1）Add Finalizer of runtime（这个需要在Get the ObjectMeta of runtime之后）
（2）AddOwnerAndRequeue
7、update status of dataset

2020-12-03 00:45 UTC, yangyuliufeng commented on pkg/ddc/alluxio/cache.go
> +		e.Log.Info("Failed to get dataset when query cache status")
@TrafalgarZZZ 由于这个方法不止是删除的时候调用，改了err的返回逻辑，还会影响其它方法的判定

2020-12-03 06:08 UTC, TrafalgarZZZ commented on pkg/ddc/alluxio/cache.go
> +		e.Log.Info("Failed to get dataset when query cache status")
@yangyuliufeng OK，同意。我只是认为这里有一个很小的Corner Case：如果`GetDataset`返回了一个不是NotFound的Error，那么`cleanupCache`端目前是不会去Check它的。

2020-12-04 03:12 UTC, closed without merging