add comment on 'RemoveString' function
fluid-cloudnative/fluid pull request #436
Opened 2020-12-03 10:32 UTC by booooooooooooom

### Ⅰ. Describe what this PR does
Add comment on 'RemoveString' function.

### Ⅱ. Does this pull request fix one issue?

fixes #22

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2020-12-03 12:05 UTC, TrafalgarZZZ requested changes

2020-12-03 12:05 UTC, TrafalgarZZZ commented on pkg/utils/crtl_utils.go
> +//Remove strings in a  array which equals to the given string.
You should use the func name as the initial word of the comment. Please change it. Thanks.

2020-12-04 03:04 UTC, cheyang commented
@booooooooooooom Could you open a new PR? the current PR is conflict now.

2020-12-04 04:40 UTC, booooooooooooom commented
> @booooooooooooom Could you open a new PR? the current PR is conflict now.

ok

2020-12-04 04:41 UTC, closed without merging