Fix code scanning alert - Prefer COPY over ADD
fluid-cloudnative/fluid pull request #4378
Opened 2024-10-27 12:03 UTC by omerap12

### Ⅰ. Describe what this PR does
Fix code scanning alert - Replace `ADD` in Dockerfiles to `COPY` 

### Ⅱ. Does this pull request fix one issue?

fixes #4354 

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2024-10-30 02:07 UTC, cheyang requested changes

2024-10-30 02:07 UTC, cheyang commented on addons/nfs/docker/Dockerfile
>  CMD ["/usr/local/bin/entrypoint.sh"]
Please add return of line.

2024-10-30 07:22 UTC, omerap12 commented on addons/nfs/docker/Dockerfile
>  CMD ["/usr/local/bin/entrypoint.sh"]
Sure :)

2024-10-31 10:17 UTC, cheyang commented
@omerap12 Please don't change [vendor/github.com/nxadm/tail/Dockerfile](https://github.com/fluid-cloudnative/fluid/pull/4378#diff-c20a3d650562db23139c78673ffd21a00b1f9c303545612964afb264d8bf9586)

2024-10-31 10:21 UTC, omerap12 commented
> @omerap12 Please don't change [vendor/github.com/nxadm/tail/Dockerfile](https://github.com/fluid-cloudnative/fluid/pull/4378#diff-c20a3d650562db23139c78673ffd21a00b1f9c303545612964afb264d8bf9586)

Yeap, sorry :(

2024-10-31 11:44 UTC, cheyang approved these changes
/lgtm
/approve

2024-10-31 11:56 UTC, merged