add commit on ContainsString
fluid-cloudnative/fluid pull request #462
Opened 2020-12-10 12:39 UTC by NKCS1341530396

### Ⅰ. Describe what this PR does

 add commit on “ContainsString” function
### Ⅱ. Does this pull request fix one issue?

Fix #460 

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

add commit
### Ⅴ. Special notes for reviews

2020-12-10 15:19 UTC, xieydd requested changes

2020-12-10 15:19 UTC, xieydd commented on pkg/utils/crtl_utils.go
> +//Determine whether the string array contains a specific string, return true if contains the string and return false if not.
add a space here : )

2020-12-10 16:16 UTC, TrafalgarZZZ requested changes
Please use func name(e.g. `ContainsString`) as the inital word of the comments. Thanks.

2020-12-11 12:47 UTC, cheyang requested changes

2020-12-11 12:47 UTC, cheyang commented on pkg/utils/crtl_utils.go
> +// Determine whether the string array contains a specific string, return true if contains the string and return false if not.
ContainsString determines whether the string array contains a specific string, return true if contains the string and return false if not.

2020-12-11 16:19 UTC, cheyang approved these changes

2020-12-11 16:19 UTC, merged