Add Fluid monitoring
fluid-cloudnative/fluid pull request #466
Opened 2020-12-14 03:54 UTC by xieydd

### Ⅰ. Describe what this PR does
Add Fluid monitoring doc and config file

### Ⅱ. Does this pull request fix one issue?
fixes #413 

### Ⅴ. Special notes for reviews
@cheyang @TrafalgarZZZ @yangyuliufeng

2020-12-14 03:57 UTC, cheyang commented on docs/zh/userguide/monitoring.md
> +$ kubectl apply -f kubernetes-artifacts/prometheus.yaml
建议放到monitoring的文件夹。

2020-12-14 04:22 UTC, cheyang requested changes

2020-12-14 04:22 UTC, cheyang commented on docs/zh/userguide/monitoring.md
> +如集群内有 prometheus,可将一下配置写到 prometheus 配置文件中:
一下配置->以下配置

2020-12-14 04:26 UTC, cheyang requested changes

2020-12-14 04:26 UTC, cheyang commented on docs/zh/userguide/monitoring.md
> +grafana 选择导入模板 Json 文件 `fluid-prometheus-grafana-monitor.json`
fluid-prometheus-grafana-monitor.json的文件位置在哪里？

2020-12-14 05:35 UTC, xieydd commented on docs/zh/userguide/monitoring.md
> +$ kubectl apply -f kubernetes-artifacts/prometheus.yaml
fix

2020-12-14 05:35 UTC, xieydd commented on docs/zh/userguide/monitoring.md
> +如集群内有 prometheus,可将一下配置写到 prometheus 配置文件中:
fix

2020-12-14 05:35 UTC, xieydd commented on docs/zh/userguide/monitoring.md
> +grafana 选择导入模板 Json 文件 `fluid-prometheus-grafana-monitor.json`
忘记了，fixed

2020-12-15 05:40 UTC, XIAO-HOU approved these changes

2020-12-15 07:42 UTC, cheyang approved these changes

2020-12-15 07:42 UTC, merged

2020-12-15 07:44 UTC, cheyang commented
优化工作可以通过这个issue跟进： https://github.com/fluid-cloudnative/fluid/issues/473