make csi-address can be configurable
fluid-cloudnative/fluid pull request #468
Opened 2020-12-14 09:24 UTC by wangandyang

### Ⅰ. Describe what this PR does

### Ⅱ. Does this pull request fix one issue?

fixes #378

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2020-12-14 09:55 UTC, xieydd requested changes

2020-12-14 09:55 UTC, xieydd commented on charts/fluid/fluid/templates/csi/daemonset.yaml
> +            - --csi-address={{ .Values.csi.kubelet.rootdir }}/csi-plugins/fuse.csi.fluid.io/csi.sock
how about change rootdir to rootDir?

2020-12-14 10:09 UTC, wangandyang commented on charts/fluid/fluid/templates/csi/daemonset.yaml
> +            - --csi-address={{ .Values.csi.kubelet.rootdir }}/csi-plugins/fuse.csi.fluid.io/csi.sock
it has changed

2020-12-14 10:28 UTC, xieydd approved these changes
/lgtm

2020-12-15 00:35 UTC, cheyang commented
Thanks, @wangandyang

2020-12-15 00:35 UTC, cheyang approved these changes

2020-12-15 00:35 UTC, merged