add owner of dataload
fluid-cloudnative/fluid pull request #483
Opened 2020-12-18 05:20 UTC by yangyuliufeng

### Ⅰ. Describe what this PR does
in the fluid-cloudnative/fluid/pull/444, deleting the dataset will delete the alluxioruntime.
I add the owner of dataload now, so that deleting the dataset will not only delete alluxioruntime but also delete dataload. 

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it
create a dataset and then create a dataload , the dataset will be the owner of dataload.
create a dataload without a dataset, the dataload will have no owner and finalizer.

### Ⅴ. Special notes for reviews

2020-12-18 07:32 UTC, cheyang requested changes

2020-12-18 07:32 UTC, cheyang commented on pkg/controllers/v1alpha1/dataload/dataload_controller.go
> +	// 3. get the dataset
getDataset这部分逻辑是不是可以放到中，如果owner已经存在就不用获取dataset了
```
	//  5. add owner and requeue
```

2020-12-21 01:33 UTC, yangyuliufeng commented on pkg/controllers/v1alpha1/dataload/dataload_controller.go
> +	// 3. get the dataset
目前的ContainsOwners函数，需要根据dataset的UID去判断owner是否存在，如果不先getDataset，就没办法判断了。
此外，我这么修改还有一个原因，我把getDataset放在了add finalizer之前，如果dataset还未创建就不会给dataload添加finalizer了。

2020-12-22 03:27 UTC, cheyang commented on pkg/controllers/v1alpha1/dataload/dataload_controller.go
> +	// 3. get the dataset
收到，谢谢。

2020-12-22 03:28 UTC, cheyang commented on pkg/controllers/v1alpha1/dataload/dataload_controller.go
> +// AddOwnerAndRequeue add Owner and requeue
```suggestion
// AddOwnerAndRequeue adds Owner and requeue
```

2020-12-22 07:13 UTC, merged