update docs for dataset secret
fluid-cloudnative/fluid pull request #485
Opened 2020-12-18 07:37 UTC by XIAO-HOU

### Ⅰ. Describe what this PR does
Updata doc accroding to the PR "Support secret for dataset". If it is ok. I will update the doc in English as well.

### Ⅱ. Does this pull request fix one issue?

NONE
### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2020-12-18 07:58 UTC, cheyang requested changes

2020-12-18 07:58 UTC, cheyang commented on docs/zh/samples/machinelearning.md
> +# 示例 - 用Fluid加速机器学习训练
能否写一个单独的文档，对于用户来说这个文档太长了

2020-12-18 08:52 UTC, XIAO-HOU commented on docs/zh/samples/machinelearning.md
> +# 示例 - 用Fluid加速机器学习训练
已经创建了单独文档，请您审核。

2020-12-18 10:58 UTC, TrafalgarZZZ requested changes

2020-12-18 10:58 UTC, TrafalgarZZZ commented on docs/zh/samples/use_encryptoptions.md
> +      - --fuse-opts=kernel_cache,ro,max_read=131072,attr_timeout=7200,entry_timeout=7200,nonempty,max_readahead=0
这些配置可以使用默认值吧?

2020-12-18 13:43 UTC, XIAO-HOU commented on docs/zh/samples/use_encryptoptions.md
> +      - --fuse-opts=kernel_cache,ro,max_read=131072,attr_timeout=7200,entry_timeout=7200,nonempty,max_readahead=0
已修正

2020-12-19 07:19 UTC, cheyang requested changes

2020-12-19 07:19 UTC, cheyang commented on docs/zh/samples/machinelearning.md
> +# 示例 - 用Fluid加速机器学习训练
那这个文件为什么还要修改呢？

2020-12-19 07:23 UTC, cheyang commented on docs/zh/samples/machinelearning.md
> +# 示例 - 用Fluid加速机器学习训练
而且修改的内容有点多。

2020-12-19 07:24 UTC, XIAO-HOU commented
这个好像是github的问题，文件内容和原来是一致的。我把之前的改动删掉了，它可能认为我添加了一个新的文件。@cheyang

2020-12-19 07:26 UTC, XIAO-HOU commented on docs/zh/samples/machinelearning.md
> +# 示例 - 用Fluid加速机器学习训练
这个好像是github的问题，文件内容和原来是一致的。我把之前的改动删掉了，它可能认为我添加了一个新的文件。

2020-12-19 07:32 UTC, XIAO-HOU commented on docs/zh/samples/machinelearning.md
> +# 示例 - 用Fluid加速机器学习训练
已解决。换行符不一致的问题。

2020-12-20 07:18 UTC, cheyang approved these changes

2020-12-20 07:18 UTC, merged