Add multi dataset in single node swicth
fluid-cloudnative/fluid pull request #486
Opened 2020-12-18 09:43 UTC by xieydd

### Ⅰ. Describe what this PR does
Add multi dataset in single node swicth.
In next pr, i will solve this condition, if no nodeAffinity with new dataset and runtime and it will not assigned to alreadyAssigned node.

### Ⅱ. Does this pull request fix one issue?
#481

2020-12-19 07:12 UTC, cheyang requested changes

2020-12-19 07:12 UTC, cheyang commented on api/v1alpha1/alluxioruntime_types.go
> +	Exclusiveness bool `json:"exclusiveness,omitempty"`
这个exlusive可能还是需要仔细想一下。

1.当runtime被部署下去，如果是exclusive，不止是它不强占别人已经运行的节点，也不能被别人抢占。
2.这个通常是调度器的通用配置，在runtime级别做是不是太复杂了。

2020-12-19 09:55 UTC, xieydd commented on api/v1alpha1/alluxioruntime_types.go
> +	Exclusiveness bool `json:"exclusiveness,omitempty"`
AFAIK
1. 目前的调度逻辑：
    dataset 指定 nodeAffinity，runtime 调度到哪个节点
    单点支持多 dataset 逻辑：两个 dataset 指定相同的 nodeAffinity, 端口查询避免冲突，缓存隔离等
    这里的 Exclusiveness 是在管理员知道那两个节点上无 runtime ,为了两个 dataset 指定不同的 nodeAffinity 后，runtime 组件端口是 default
2. 期望的调度逻辑：
    指定 Exclusiveness 后，如果管理员指定 nodeAffinity 上对应的节点存在 runtime, 此 runtime 将不会调度到该节点，同时如果调度到空闲节点后，该节点设置不可再调度 runtime 到该节点。

赞同在调度器配置，掉对齐有拆出来计划吗，我只看到 scheduler.go `AssignDatasetToNodes` 方法

2020-12-24 17:43 UTC, cheyang requested changes

2020-12-24 17:43 UTC, cheyang commented on pkg/ddc/base/label.go
> +	return common.LabelAnnotationStorageCapacityPrefix + info.runtimeType + "-" + common.Exclusiveness
是不是exclusive的标签是全局唯一的？

2020-12-24 17:49 UTC, cheyang requested changes

2020-12-24 17:49 UTC, cheyang commented on pkg/ddc/base/label.go
> +	return common.LabelAnnotationStorageCapacityPrefix + info.runtimeType + "-" + common.Exclusiveness
是不是可以简化为IsExclusive?然后打一个通用label： exclusive=true

2020-12-24 17:56 UTC, cheyang requested changes

2020-12-24 17:56 UTC, cheyang commented on pkg/ddc/alluxio/master_internal.go
> +func (e *AlluxioEngine) setupMasterInternal() (err error) {
好眼力

2020-12-24 17:56 UTC, cheyang commented on pkg/utils/dataset/lifecycle/node.go
> +	label := runtimeInfo.GetRuntimeExclusivenessLabelname()
这里的独占应该是不与任何其他runtime共享，不只是该runtime自身？

2020-12-24 17:57 UTC, cheyang requested changes

2020-12-24 17:57 UTC, cheyang commented on pkg/utils/dataset/lifecycle/node.go
> +func LabelCacheNode(nodeToLabel v1.Node, runtimeInfo base.RuntimeInfoInterface, client client.Client, exclusiveness bool) (err error) {
可否，不增加exclusiveness bool，因为runtimeInfo已经包含exclusive的信息了

2020-12-24 17:59 UTC, cheyang commented
1. 是否可以在初始化engine的时候将runtimeInfo中增加exclusive为true, 之后打一个通用的label： fluid_exclusive=true
2. crd的yaml需要更新

2020-12-25 02:51 UTC, xieydd commented on pkg/ddc/base/label.go
> +	return common.LabelAnnotationStorageCapacityPrefix + info.runtimeType + "-" + common.Exclusiveness
tks, fix

2020-12-25 02:51 UTC, xieydd commented on pkg/ddc/alluxio/master_internal.go
> +func (e *AlluxioEngine) setupMasterInternal() (err error) {
强迫症

2020-12-25 02:51 UTC, xieydd commented on pkg/utils/dataset/lifecycle/node.go
> +	label := runtimeInfo.GetRuntimeExclusivenessLabelname()
tks, fix

2020-12-25 02:51 UTC, xieydd commented on pkg/utils/dataset/lifecycle/node.go
> +func LabelCacheNode(nodeToLabel v1.Node, runtimeInfo base.RuntimeInfoInterface, client client.Client, exclusiveness bool) (err error) {
tks, fix

2020-12-25 04:27 UTC, cheyang requested changes

2020-12-25 04:27 UTC, cheyang commented on api/v1alpha1/dataset_types.go
> +	Exclusiveness bool `json:"exclusiveness,omitempty"`
exclusiveMode如何？

2020-12-25 04:30 UTC, cheyang requested changes

2020-12-25 04:30 UTC, cheyang commented on pkg/ddc/base/runtime.go
> +	GetRuntimeExclusiveLabelname() string
这个方法不需要作为接口方法实现吧？

2020-12-25 05:43 UTC, xieydd commented on api/v1alpha1/dataset_types.go
> +	Exclusiveness bool `json:"exclusiveness,omitempty"`
tks,fix

2020-12-25 05:43 UTC, xieydd commented on pkg/ddc/base/runtime.go
> +	GetRuntimeExclusiveLabelname() string
fix, tks

2020-12-25 07:41 UTC, TrafalgarZZZ commented on pkg/utils/dataset/lifecycle/node.go
> +	}
按照这里的逻辑，如果某node上已经有`common.Exclusive`标签，那么该结点不会再被后续的Dataset占用。但是，如果已有一个non-Exclusive的Dataset占用了该node，新的Exclusive的Dataset是不是也不能占用该node呢？

2020-12-25 07:48 UTC, xieydd commented on pkg/utils/dataset/lifecycle/node.go
> +	}
是的，这种情况下漏考虑，感谢

2020-12-25 11:38 UTC, xieydd commented on pkg/utils/dataset/lifecycle/node.go
> +	}
@TrafalgarZZZ Fixed, cc

2020-12-27 05:21 UTC, merged