fix pic url
fluid-cloudnative/fluid pull request #494
Opened 2020-12-21 07:47 UTC by yangyuliufeng

### Ⅰ. Describe what this PR does
add the pic in the doc of adding new runtime

### Ⅱ. Does this pull request fix one issue?

#484 

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2020-12-21 08:14 UTC, xieydd requested changes

2020-12-21 08:14 UTC, xieydd commented on docs/zh/dev/runtime_dev_guide.md
> +![dataset](https://github.com/fluid-cloudnative/fluid/blob/master/static/dataset_lifecycle.png)
How about relative paths?

2020-12-24 01:09 UTC, yangyuliufeng commented on docs/zh/dev/runtime_dev_guide.md
> +![dataset](https://github.com/fluid-cloudnative/fluid/blob/master/static/dataset_lifecycle.png)
@xieydd 更改到了../../media/images

2020-12-24 01:35 UTC, xieydd commented on docs/zh/dev/runtime_dev_guide.md
> +![dataset](https://github.com/fluid-cloudnative/fluid/blob/master/static/dataset_lifecycle.png)
@yangyuliufeng Have not seen changed?

2020-12-24 01:38 UTC, xieydd approved these changes
/lgtm

2020-12-25 00:26 UTC, cheyang approved these changes

2020-12-25 00:26 UTC, merged