add the crd of databackup to backup the metadata file and metadata info file
fluid-cloudnative/fluid pull request #533
Opened 2021-01-06 15:59 UTC by yangyuliufeng

### Ⅰ. Describe what this PR does
This PR adds the crd of DataBackup
When user creating a DataBackup, it will create a pod to backup the metadata file and metadata info file（ufs total and filenum info）
The CRD supports the path in form of local://xxxx and pvc://{$pvcname}/xxxxxx
### Ⅱ. Does this pull request fix one issue?

#384 

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it
You can create the following yaml file to verify it
```yaml
apiVersion: data.fluid.io/v1alpha1
kind: DataBackup
metadata:
  name: hbase-backup
spec:
  dataset: hbase
  backupPath: local://subpath/subpath
  # backupPath: pvc://{$pvcname}/subpath
```

### Ⅴ. Special notes for reviews
This PR only supports backuping, not supporting restoring.

2021-01-06 16:04 UTC, cheyang requested changes

2021-01-06 16:04 UTC, cheyang commented on Dockerfile.databackup
> +CMD ["databackup", "start"]
能否不使用registry.cn-huhehaote.aliyuncs.com/alluxio/alluxio:2.3.0-SNAPSHOT-985b84c， 因为alluxio的镜像更新速度比较快。而是通过把脚本放到configmap里来实现？

2021-01-06 16:05 UTC, cheyang commented on charts/alluxio/templates/master/statefulset.yaml
> +            path: /alluxio_backups
1.根目录不一定有写权限
2.多个master pod如果在同一个节点会发生冲突

2021-01-06 16:08 UTC, cheyang commented
请修复一下CI，谢谢。

2021-01-07 04:30 UTC, cheyang requested changes

2021-01-07 04:30 UTC, cheyang commented on cmd/alluxio/main.go
> +	if err = (databackupctl.NewDataBackupReconciler(mgr.GetClient(),
应该放到dataset controller里会比较合适。

2021-01-07 06:17 UTC, xieydd reviewed
Nice work!

2021-01-07 06:17 UTC, xieydd commented on pkg/controllers/v1alpha1/databackup/implement.go
> +	// 1. Check if there's any Backinging pods(conflict DataBackup)
Backing?

2021-01-07 13:07 UTC, yangyuliufeng commented on charts/alluxio/templates/master/statefulset.yaml
> +            path: /alluxio_backups
目前通过将备份文件名设置为metadata-backup-{$DatasetName}-{$Namespace}.gz来避免冲突

2021-01-07 13:08 UTC, yangyuliufeng commented on pkg/controllers/v1alpha1/databackup/implement.go
> +	// 1. Check if there's any Backinging pods(conflict DataBackup)
应该是Backuping

2021-01-17 04:38 UTC, TrafalgarZZZ commented on pkg/utils/docker/image.go
> +func GetAlluxioWorkerImage(client client.Client, datasetName string, namespace string)(imageName string, imageTag string){
这里获取runtime的Image信息如果改为`xxx-alluxio-values`的ConfigMap里抽取可行吗？这样就可以不用在dataset-controller里注入`ALLUXIO_RUNTIME_IMAGE_ENV`的环境变量了，以ConfigMap中的Image信息为准

2021-01-18 10:48 UTC, yangyuliufeng commented on pkg/utils/docker/image.go
> +func GetAlluxioWorkerImage(client client.Client, datasetName string, namespace string)(imageName string, imageTag string){
> 这里获取runtime的Image信息如果改为`xxx-alluxio-values`的ConfigMap里抽取可行吗？这样就可以不用在dataset-controller里注入`ALLUXIO_RUNTIME_IMAGE_ENV`的环境变量了，以ConfigMap中的Image信息为准

当然是可行的。ConfigMap存的是部署alluxio的配置，里面的镜像版本和alluxio-work的镜像版本、环境变量里的镜像版本是完全一致的。这样改的话，好处是不再需要注入环境变量，不过读取configmap的实现要比读取环境变量麻烦。

2021-01-18 12:52 UTC, XIAO-HOU commented on pkg/controllers/v1alpha1/dataload/implement.go
> +	imageName, imageTag := docker.GetAlluxioWorkerImage(r.Client, dataload.Spec.Dataset.Name, dataload.Spec.Dataset.Namespace)
这里抽取runtime镜像通过抽象出一个类似GetRuntimeImage()的方法是不是更好一些，runtime分很多种，这样写不同的runtime可以对这个方法有不同实现。现在的实现是固定抽取alluxioruntime镜像，如果底层用的是jindoruntime是不是又要改代码了。

2021-01-19 01:33 UTC, xieydd commented on pkg/controllers/v1alpha1/dataload/implement.go
> +	imageName, imageTag := docker.GetAlluxioWorkerImage(r.Client, dataload.Spec.Dataset.Name, dataload.Spec.Dataset.Namespace)
同意，建议抽象出 common function

2021-01-20 06:32 UTC, yangyuliufeng commented on pkg/controllers/v1alpha1/dataload/implement.go
> +	imageName, imageTag := docker.GetAlluxioWorkerImage(r.Client, dataload.Spec.Dataset.Name, dataload.Spec.Dataset.Namespace)
> 这里抽取runtime镜像通过抽象出一个类似GetRuntimeImage()的方法是不是更好一些，runtime分很多种，这样写不同的runtime可以对这个方法有不同实现。现在的实现是固定抽取alluxioruntime镜像，如果底层用的是jindoruntime是不是又要改代码了。

刚刚讨论了一下，准备用读取configmap的方法获取镜像版本。以后接入jindoruntime的时候，同样需要它们把镜像版本写入到configmap中

2021-01-24 10:57 UTC, cheyang commented on docs/zh/samples/backup_and_restore_metadata.md
> +* 数据集的metadata
能否提供一下具体的例子，比如metadata包括什么；统计信息包括什么。谢谢

2021-01-31 15:32 UTC, cheyang requested changes

2021-01-31 15:32 UTC, cheyang commented on charts/fluid-databackup/templates/databackup.yaml
> +              mode: 365
Add return of line

2021-01-31 15:32 UTC, cheyang commented on charts/fluid-databackup/values.yaml
> +databackuper:
建议此处改成dataBackup,用驼峰式定义。下面的databackup改成name

2021-01-31 15:39 UTC, cheyang commented on pkg/controllers/v1alpha1/databackup/databackup_controller.go
> +	ctx.Log.V(1).Info("DataBackup found", "detail", databackup)
建议去掉V(1)

2021-01-31 15:44 UTC, cheyang commented on charts/alluxio/values.yaml
> +  backupPath: /tmp/alluxio-backup/default/hbase
这个目录是动态生成的吗？

2021-01-31 15:46 UTC, cheyang requested changes

2021-01-31 15:46 UTC, cheyang commented on api/v1alpha1/databackup_types.go
> +type DataBackupStatus struct {
这里要加一下// +kubebuilder:subresource:status

2021-01-31 15:51 UTC, cheyang commented on docs/zh/samples/backup_and_restore_metadata.md
> +在部署Fluid时，可以通过修改charts中values.yaml中的workdir，配置Fluid工作目录，默认为/tmp目录：
这里需要解释一下workDir用来做什么？比如备份元数据。否则用户可能不太理解修改workerDir的目的。

2021-01-31 15:53 UTC, cheyang commented on docs/zh/samples/backup_and_restore_metadata.md
> +$ kubectl get databackup
请问目前可以知道备份花费时间吗？如果没有可以开一个issue跟进。

2021-02-01 06:13 UTC, yangyuliufeng commented on docs/zh/samples/backup_and_restore_metadata.md
> +$ kubectl get databackup
> 请问目前可以知道备份花费时间吗？如果没有可以开一个issue跟进。

目前没用计算备份花费的时间，还有备份文件的大小其实未来也需要关注下

2021-02-01 06:14 UTC, yangyuliufeng commented on charts/alluxio/values.yaml
> +  backupPath: /tmp/alluxio-backup/default/hbase
> 这个目录是动态生成的吗？我担心多个dataset会有冲突

动态生成的。我把这里去掉。

2021-02-01 07:25 UTC, cheyang commented on charts/fluid-databackup/Chart.yaml
> +name: fluid-databacker
我个人觉得还是叫fluid-data-backup好一点

2021-02-01 09:17 UTC, cheyang approved these changes

2021-02-01 09:18 UTC, merged