Show dataload duration time
fluid-cloudnative/fluid pull request #540
Opened 2021-01-18 13:57 UTC by XIAO-HOU

### Ⅰ. Describe what this PR does
show dataload duration time in a simple way.

### Ⅱ. Does this pull request fix one issue?

NONE

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2021-01-19 01:30 UTC, xieydd approved these changes
/lgtm

2021-01-20 06:28 UTC, cheyang requested changes

2021-01-20 06:28 UTC, cheyang commented on pkg/controllers/v1alpha1/dataload/implement.go
> +				dataloadToUpdate.Status.DurationTime = jobCondition.LastProbeTime.Sub(dataloadToUpdate.CreationTimestamp.Time).String()
是不是应该是上一次发生transition的时间戳？

2021-01-20 12:18 UTC, XIAO-HOU commented on pkg/controllers/v1alpha1/dataload/implement.go
> +				dataloadToUpdate.Status.DurationTime = jobCondition.LastProbeTime.Sub(dataloadToUpdate.CreationTimestamp.Time).String()
是的，已改正

2021-01-23 07:28 UTC, merged