Enhance log and Event reporting when the dataset cannot being deleted
fluid-cloudnative/fluid pull request #544
Opened 2021-01-21 00:50 UTC by yangyuliufeng

### Ⅰ. Describe what this PR does
when I tried to delete dataset, it will hang because the pod which uses pvc is not deleted.
I Enhance log and Event reporting when the dataset cannot being deleted

### Ⅱ. Does this pull request fix one issue?

#535 

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it
create a pod to use the pvc, and the delete the dataset

### Ⅴ. Special notes for reviews

2021-01-22 03:28 UTC, cheyang requested changes

2021-01-22 03:28 UTC, cheyang commented on pkg/controllers/v1alpha1/dataset/dataset_controller.go
> +		err := fmt.Errorf("dataset cannot be deleted because pvc is mounted or err appear when querying pvc")
具体的error信息建议透出，否则排查问题方向难以确定

2021-01-25 02:29 UTC, xieydd commented on pkg/controllers/v1alpha1/dataset/dataset_controller.go
> +		ctx.Log.Error(err, "Failed to delete dataset because pvc is mounted", "DatasetDeleteError", ctx)
这里日志是否重复？

2021-01-25 06:43 UTC, cheyang requested changes

2021-01-25 06:43 UTC, cheyang commented on pkg/controllers/v1alpha1/dataset/dataset_controller.go
> +		r.Recorder.Eventf(&ctx.Dataset, v1.EventTypeWarning, common.ErrorDeleteDataset, "dataset %s cannot be deleted because cannot get PVC or PvcMountPods", ctx.Dataset.Name)
err的原因在recorder中是否需要记录？比如err.Error()之类?

2021-01-25 10:26 UTC, yangyuliufeng commented on pkg/controllers/v1alpha1/dataset/dataset_controller.go
> +		ctx.Log.Error(err, "Failed to delete dataset because pvc is mounted", "DatasetDeleteError", ctx)
> 这里日志是否重复？

是有重复，err里已经有的信息其实没必须再打出来一遍了

2021-01-28 05:55 UTC, merged