Add Governance Principle
fluid-cloudnative/fluid pull request #552
Opened 2021-01-30 07:55 UTC by cheyang

Signed-off-by: cheyang <cheyang@163.com>

### Ⅰ. Describe what this PR does

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2021-01-31 12:29 UTC, TrafalgarZZZ approved these changes

2021-02-01 05:40 UTC, apc999 requested changes

2021-02-01 05:40 UTC, apc999 commented on GOVERNANCE.md
> +* Classify GitHub issues and perform pull request reviews for other maintainers and the community.
Curate github issues and review pull requests

2021-02-01 05:40 UTC, apc999 commented on GOVERNANCE.md
> +* During GitHub issue classification, apply all applicable [labels](https://github.com/fluid-cloudnative/fluid/labels)
Remove " During GitHub issue classification"

2021-02-01 05:40 UTC, apc999 commented on GOVERNANCE.md
> +  to each new issue. Use your best judgement to apply labels, since they are extremely useful for follow-up of future issues.
Try your best to label issues which are very helpful and set a good example for future issues.

2021-02-01 05:40 UTC, apc999 commented on GOVERNANCE.md
> +* Participate when called upon in the security release process. Note
not sure what you want to express here. Can you rephrase?

2021-02-01 05:40 UTC, apc999 commented on GOVERNANCE.md
> +* In general continue to be willing to spend at least 20% of your time working on Fluid (1 day per week).
Expect to spend 20% time ...

2021-02-01 05:40 UTC, apc999 commented on GOVERNANCE.md
> +* We will expect you to start contributing increasingly complicated PRs, under the guidance of the existing maintainers.
We will expect you to start contributing pull requests with increasing complexity ...

2021-02-01 05:40 UTC, apc999 commented on GOVERNANCE.md
> +* After a period of approximately 3 months of working together and making sure we see eye to eye, the existing
what does "eye to eye" mean here?

2021-02-01 05:40 UTC, apc999 commented on GOVERNANCE.md
> +Some contents in this documents have been borrowed from [libvineyard](https://github.com/alibaba/libvineyard/blob/main/GOVERNANCE.md)
This document references the GOVERNANCE guide from xxx and yyy

2021-02-01 05:40 UTC, apc999 commented on GOVERNANCE.md
> +Proposals and ideas can either be submitted for agreement via a github issue or PR.
PR -> pull request , let's not use abbreviation in formal docs

2021-02-01 05:40 UTC, apc999 commented on CODE_OF_CONDUCT.md
> +In cases of abusive, harassing, or any unacceptable behaviors, please don't hesitate to contact the [maintainers](MAINTAINERS.md).
don't -> do not

2021-02-01 05:40 UTC, apc999 commented on GOVERNANCE.md
> +* We may ask you to do some PRs from our backlog. As you gain experience with the code base and our standards,
We recommend you to take pull requests from the backlog.
As one grow more experienced and familiar with the code base and standards,
we expect him/her to review more pull requests

2021-02-01 05:40 UTC, apc999 commented
language polish. Please take a look

2021-02-02 01:51 UTC, RongGu commented on MAINTAINERS.md
> +| [Rong Gu](mailto:gurongwalker@gmail.com) | [RongGu](https://github.com/RongGu) | Nanjing University |
My main email address is gurong@nju.edu.cn, thanks!

2021-02-02 03:34 UTC, apc999 approved these changes

2021-02-02 03:54 UTC, merged