Support non-default configurations for HDFS
fluid-cloudnative/fluid pull request #561
Opened 2021-02-02 15:57 UTC by TrafalgarZZZ

### Ⅰ. Describe what this PR does
When using HDFS as Alluxio's UFS, Alluxio may need additional HDFS configuraions (e.g. `hdfs-site.xml` and `core-site.xml`) to enable some features. For now, there is no way for Fluid's user to specify their HDFS conf files. 

This PR supports non-default configuration for HDFS with the following workflow:
1. user creates a configmap from HDFS conf file(s). (Only support `hdfs-site.xml` and `core-site.xml` for now)
2. user specifies the configmap name in AlluxioRuntime
3. Fluid mounts the configmap to Alluxio's Pods and enables special features for HDFS.

### Ⅱ. Does this pull request fix one issue?

fixes #502 

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it
1. Create configmap from HDFS conf file
```
kubectl create configmap hdfs-cm --from-file=/path/to/hdfs-site.xml --from-file=/path/to/core-site.xml
```

2. Create Dataset and AlluxioRuntime with `hadoopConfig` set to the name of the configmap:
```
---
apiVersion: data.fluid.io/v1alpha1
kind: AlluxioRuntime
metadata:
  ...
spec:
  ...
  hadoopConfig: hdfs-cm
  ...

```

### Ⅴ. Special notes for reviews
A user manual is also required to clearly demonstrate the workflow. The PR will become ready once the user manual is committed.

2021-02-03 02:24 UTC, xieydd requested changes
Good work.

2021-02-03 02:24 UTC, xieydd commented on charts/alluxio/templates/master/statefulset.yaml
> +            {{ if .Values.hadoopConfig.includeHdfsSite -}}
- in the end is same as in start?

2021-02-03 02:24 UTC, xieydd commented on pkg/ddc/alluxio/transform_hadoop_config.go
> +// transformSecurity transforms security configuration
pls fix the func comment

2021-02-03 02:24 UTC, xieydd commented on pkg/ddc/alluxio/transform_hadoop_config.go
> +		if k == HADOOP_CONF_HDFS_SITE_FILENAME {
How about change if to switch?

2021-02-03 07:31 UTC, TrafalgarZZZ commented on charts/alluxio/templates/master/statefulset.yaml
> +            {{ if .Values.hadoopConfig.includeHdfsSite -}}
Yes, they have same effect.

2021-02-03 07:31 UTC, TrafalgarZZZ commented on pkg/ddc/alluxio/transform_hadoop_config.go
> +// transformSecurity transforms security configuration
Fixed

2021-02-03 07:31 UTC, TrafalgarZZZ commented on pkg/ddc/alluxio/transform_hadoop_config.go
> +		if k == HADOOP_CONF_HDFS_SITE_FILENAME {
Good suggestion. Done.

2021-02-04 02:32 UTC, xieydd approved these changes
/lgtm

2021-02-04 05:47 UTC, merged