add the function of restoring from metadata been backuped
fluid-cloudnative/fluid pull request #564
Opened 2021-02-03 02:34 UTC by yangyuliufeng

### Ⅰ. Describe what this PR does
This PR edits the crd of dataset, so that user can define a restore location to restore from metadata been backuped
It also change the logic of loading metadata and getting ufs total, fileNum
### Ⅱ. Does this pull request fix one issue?

#384

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it
@XIAO-HOU has verfied it.

### Ⅴ. Special notes for reviews

2021-02-03 06:03 UTC, xieydd requested changes
how about fix the ci check

2021-02-04 15:30 UTC, cheyang commented on pkg/ddc/alluxio/transform.go
> +	if err == nil {
`if err != nil`是一个比较直接的逻辑。另外建议增加一下注释

2021-02-04 15:32 UTC, cheyang commented on pkg/ddc/alluxio/operations/base.go
> +	case DatasetName:
能否增加文件内容的例子，方便理解这段代码的逻辑。

2021-02-04 15:33 UTC, cheyang commented on api/v1alpha1/dataset_types.go
> +	DataRestoreLocation DataRestoreLocation `json:"dataRestoreLocation,omitempty"`
可否用指针？

2021-02-05 05:59 UTC, TrafalgarZZZ commented on pkg/ddc/alluxio/metadata.go
> +				result.Err = errors.New("GetMetadataInfoFailed")
这里是不是根据具体的错误结果返回更好? 可以更精准地得知哪一步出了问题.

2021-02-05 06:01 UTC, TrafalgarZZZ commented on docs/zh/samples/backup_and_restore_metadata.md
> +在创建Datast时，在spec中添加dataRestoreLocation，填入刚刚查询到的路径和备份文件所在主机的nodeName
```suggestion
在创建Dataset时，在spec中添加dataRestoreLocation，填入刚刚查询到的路径和备份文件所在主机的nodeName
```

2021-02-05 06:01 UTC, TrafalgarZZZ commented on docs/zh/samples/backup_and_restore_metadata.md
> +在创建Datast时，在spec中添加dataRestoreLocation，填入刚刚查询到的路径作为恢复路径
```suggestion
在创建Dataset时，在spec中添加dataRestoreLocation，填入刚刚查询到的路径作为恢复路径
```

2021-02-06 00:13 UTC, yangyuliufeng commented on pkg/ddc/alluxio/metadata.go
> +				result.Err = errors.New("GetMetadataInfoFailed")
> 这里是不是根据具体的错误结果返回更好? 可以更精准地得知哪一步出了问题.

这里有可能发生了多种错误，所以我统一回了一个GetMetadataInfoFailed

2021-02-07 04:06 UTC, cheyang commented on pkg/ddc/alluxio/metadata.go
> +				result.Err = errors.New("GetMetadataInfoFailed")
具体错误如何诊断？有什么办法不？

2021-02-09 09:37 UTC, merged