Support toleration and fix exclusive label deletion issue
fluid-cloudnative/fluid pull request #578
Opened 2021-02-06 11:48 UTC by cheyang

### Ⅰ. Describe what this PR does

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2021-02-07 03:02 UTC, xieydd requested changes

2021-02-07 03:02 UTC, xieydd commented on docs/zh/samples/data_toleration.md
> +  nodeAffinity:
nodeAffinity will to tolerance?

2021-02-08 11:27 UTC, cheyang commented on docs/zh/samples/data_toleration.md
> +  nodeAffinity:
I've updated the docs

2021-02-08 11:27 UTC, cheyang commented on pkg/utils/dataset/lifecycle/schedule.go
> +		if !node.Spec.Unschedulable {
Done. Thanks.

2021-02-08 11:27 UTC, cheyang commented on docs/zh/samples/data_toleration.md
> +kubectl taint nodes node1 key=value:NoSchedule
updated

2021-02-08 15:06 UTC, xieydd requested changes

2021-02-08 15:06 UTC, xieydd commented on docs/zh/samples/data_toleration.md
> +$ kubectl label node cn-beijing.192.168.1.147 hbase-cache-
No use of 147 node.
```
kubectl taint nodes cn-beijing.192.168.1.146 hbase-cache-
```

2021-02-09 01:54 UTC, xieydd commented on docs/zh/samples/data_toleration.md
> +$ kubectl label node cn-beijing.192.168.1.147 hbase-cache-
Others, /lgtm

2021-02-09 02:29 UTC, cheyang commented on docs/zh/samples/data_toleration.md
> +$ kubectl label node cn-beijing.192.168.1.147 hbase-cache-
thx

2021-02-09 02:47 UTC, TrafalgarZZZ approved these changes
/lgtm

2021-02-09 02:52 UTC, merged