optimize  the implementation of calculating duration
fluid-cloudnative/fluid pull request #645
Opened 2021-03-22 10:21 UTC by yangyuliufeng

### Ⅰ. Describe what this PR does
optimize  the implementation  of  calculating duration
including databackup, dataload the the setup duration of alluxioruntime
### Ⅱ. Does this pull request fix one issue?

#595

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2021-03-23 10:44 UTC, iluoeli approved these changes

2021-03-24 07:52 UTC, cheyang requested changes

2021-03-24 07:52 UTC, cheyang commented on pkg/controllers/v1alpha1/databackup/implement.go
> +		databackupToUpdate.Status.Duration = utils.CalculateDuration(databackupToUpdate.CreationTimestamp.Time)
这个应该是Pod的完成时间-databakcup时间吧？

2021-03-24 10:40 UTC, yangyuliufeng commented on pkg/controllers/v1alpha1/databackup/implement.go
> +		databackupToUpdate.Status.Duration = utils.CalculateDuration(databackupToUpdate.CreationTimestamp.Time)
> 这个应该是Pod的完成时间-databakcup时间吧？

是的，这里是拿当前时间-databakcup的create时间，其实会有几秒误差。我改一下改成PodCompleted的lastProbeTime吧

2021-03-30 12:15 UTC, cheyang approved these changes

2021-03-30 12:16 UTC, cheyang approved these changes

2021-03-30 12:16 UTC, merged