add docs for creating dataset by using go
fluid-cloudnative/fluid pull request #646
Opened 2021-03-22 11:15 UTC by XIAO-HOU

### Ⅰ. Describe what this PR does
add documents for creating Dataset and AlluxioRuntime by using go.

### Ⅱ. Does this pull request fix one issue?

NONE

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2021-03-23 09:57 UTC, cheyang requested changes

2021-03-23 09:57 UTC, cheyang commented on docs/zh/dev/use_go_create_dataset.md
> +## fluid使用Go客户端创建和删除Dataset以及AlluxioRuntime
最好能提供完整可运行的例子

2021-03-25 07:32 UTC, XIAO-HOU commented on docs/zh/dev/use_go_create_dataset.md
> +## fluid使用Go客户端创建和删除Dataset以及AlluxioRuntime
完整可运行的例子已经提供

2021-03-25 07:32 UTC, XIAO-HOU commented on docs/zh/dev/use_go_create_dataset.md
> +## fluid使用Go客户端创建和删除Dataset以及AlluxioRuntime
@cheyang

2021-03-26 03:18 UTC, cheyang approved these changes

2021-03-26 03:21 UTC, merged