Add the volume attachment problem in faq.md
fluid-cloudnative/fluid pull request #756
Opened 2021-04-26 07:04 UTC by littletiger123

### Ⅰ. Describe what this PR does
This PR adds the volume attachment in the faq.md.

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2021-04-27 02:16 UTC, cheyang requested changes

2021-04-27 02:16 UTC, cheyang commented on docs/en/userguide/faq.md
> +**Answer**: First, you need to use the command `kubectl get csidriver` to check whether CSI driver is installed.
the command should be `export KUBECONFIG=/etc/kubernetes/kubelet.conf && kubectl get csidriver`

2021-04-27 02:18 UTC, cheyang requested changes

2021-04-27 02:18 UTC, cheyang commented on docs/zh/userguide/faq.md
> +**回答**:首先需要使用命令`kubectl get csidriver`查看是否安装了 CSI Driver。
该问题是由于fluid的csidriver没有安装，或者kubelet没有访问csidriver的权限导致的。

2021-04-27 08:45 UTC, littletiger123 commented on docs/zh/userguide/faq.md
> +**回答**:首先需要使用命令`kubectl get csidriver`查看是否安装了 CSI Driver。
Fixed. Thanks for your suggestions.

2021-04-29 02:23 UTC, cheyang approved these changes

2021-04-29 02:23 UTC, merged