Fluid Python and Java client SDK
fluid-cloudnative/fluid pull request #779
Opened 2021-05-14 08:40 UTC by Rui-Tang

…lient sdk

### Ⅰ. Describe what this PR does

This PR  automatically convert Go structs to OpenAPI to JSONSchema to SDK of multiple languages

### Ⅱ. Does this pull request fix one issue?

fixes #778 

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews
We can move SDK to seperate repositoris like OpenKruise java client (https://github.com/openkruise/client-java)

2021-05-14 09:05 UTC, allenhaozi commented
It's better to have a separate repo as the SDK's repo @cheyang @RongGu

2021-05-14 15:59 UTC, cheyang commented
Yeah, we already have the repo: https://github.com/fluid-cloudnative/fluid-client-java

2021-05-15 08:44 UTC, xieydd commented
So, we will close the pr and seperate the python and java sdk to independent repo?

2021-05-17 01:57 UTC, Rui-Tang commented
> So, we will close the pr and seperate the python and java sdk to independent repo?

No, I will clean this PR, remove python and java client. Scripts to generate client code will remain.

2021-05-17 02:38 UTC, cheyang requested changes

2021-05-17 02:38 UTC, cheyang commented on hack/sdk/main.go
> +Copyright 2019 kubeflow.org.
Please update license header. Thanks.

2021-05-17 03:47 UTC, Rui-Tang commented on hack/sdk/main.go
> +Copyright 2019 kubeflow.org.
ok

2021-05-17 05:45 UTC, cheyang commented on docs/zh/dev/multiple-client-support.md
> +
Does it require Java 1.8+ ?

2021-05-17 06:03 UTC, cheyang approved these changes

2021-05-17 06:44 UTC, merged