Support mountpoint dynamic add and delete and add unit test
fluid-cloudnative/fluid pull request #956
Opened 2021-08-04 02:47 UTC by xieydd

Signed-off-by: xieydd <xieydd@gmail.com>

### Ⅰ. Describe what this PR does
Support mountpoint dynamic add and delete and add unit test

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews
cc @cheyang

2021-12-16 03:40 UTC, xieydd commented
pls cc @cheyang

2021-12-22 03:46 UTC, cheyang requested changes

2021-12-22 03:46 UTC, cheyang commented on api/v1alpha1/zz_generated.deepcopy.go
> +//go:build !ignore_autogenerated
no need to update this file.

2021-12-22 03:49 UTC, xieydd commented on api/v1alpha1/zz_generated.deepcopy.go
> +//go:build !ignore_autogenerated
tks, fix done.

2021-12-22 06:10 UTC, cheyang approved these changes

2021-12-22 06:10 UTC, merged